controllers:
  main:
    containers:
      main:
        env:
          DB_HOSTNAME: homelab-pg-rw.infra.svc.cluster.local
          DB_USERNAME: immich
          DB_PASSWORD: immich
immich:
  persistence:
    library:
      existingClaim: "immich-lib-claim"
server:
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: spnw-intermediate-ca1-issuer
        cert-manager.io/common-name: "immich.lan"
      hosts:
        - host: immich.lan
          paths:
            - path: "/"
              service:
                identifier: main
      tls:
        - secretName: immich-cert-secret
          hosts:
            - immich.lan
      
machine-learning:
  enabled: false
valkey:
  enabled: true
