apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- namespace.yaml
- argocd-server-tls.yaml
- ingress.yaml
- install.yaml

patches:
- path: argocd-cmd-params-cm.yaml
