ingress:
  enabled: true
  name: "gatus-ingress"
  hosts:
    - gatus.lan
config:
  endpoints:
    - name: immich
      url: http://immich-server.immich.svc.cluster.local:2283/healthz
      conditions:
        - "[STATUS] == 200"
    - name: postgres
      url: https://pg-health.infra.svc.cluster.local:8000/healthz
      client:
        insecure: true
      conditions:
        - "[STATUS] == 200"

