apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra 

resources:
  - secrets/freshrss-pg-secret.yaml 
  - secrets/pg-appuser-secret.yaml
  - cluster.yaml
  - service.yaml
